language: python
python:
- 3.6
env:
- PKG_NAME=limix_sphinx_theme
script:
- bash <(curl -fsSL https://raw.githubusercontent.com/horta/ci/master/travis.sh)
notifications:
  email:
    recipients:
    - danilo.horta@pm.me
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  user: dhorta
  password:
    secure: IQRARtFLeJggua482uavaLxjw95Hw8DQndg2vjXDYY+ETnOQKPfv6vUhAd05ryjHCk+heLWWoRGsiWKjV606ssYj2/knHT0ZjsTrJBNZ6f31B8L2fLDJ7bwMQB62zyBQk9lY7UU4UKxF44fUYsJdSiDn5kcIlLPYSyS3FTwGbWVarRWRiOkPG8bw9QF1qNd2Y4Wh/hMXuFjhCDptyzSrIhj2KQDLS7REFzZnuIg5XPz6nAp4TrzbNmDnaBBK4uymP6zpVZUjkvynUKAlu96vdsk5xjf6+mt7caacXjSzdSRp0UIPpfqkgG5406Ta1SKGzJ6AJKMoNBaFZCa9I4jOED/XmmcSGuV98gJzamqDHV1PHyVgzvGmvSZZbbY4PVWeApak5AlaWt43UacFR5FycxZ9u/LZdwDNavjoD88Gggm+Sk0ILR/USFfqk9OsfdTApwi7IbzXED1/7Pdd9UP3s1BDQccx6374SThe7oIlxz2G198sLncW1Nlp9yFUeu3qSa6OPosuiWR8TLpOheAtYWOUKxMoEjR3/FP5+95idjSVtFiP1dAO6yn2f8ycLtbAGibN7VaX+LauJzjqyboNR8j32MZDYsVBkQJUQmLp6KfdYXKGJxZ5uz3APtObiIbJBdAVFTTUZf+rICiyEpsat+2shhOOJMAZ6J2ZprHuSvQ=
  on:
    tags: true
    repo: limix/limix-sphinx-theme
    branch: master
    python: 3.6
